#include <stdio.h>

void hailstones(int);

int main(int argc, char *argv[])
{
    int n;
    
    printf("Input number to run hailstones on.\n");
    scanf("%d", &n);
    hailstones(n);
    
    return 0;
}

void hailstones(int n)
{
    int cnt = 1;
    
    printf("Hailstones generated by %d\n", n);
    while (n != 1){
	printf("%5d ", n);
	if (cnt % 6 == 0)
	    printf("\n");
	if (n % 2 == 0)
	    n /= 2;
	else
	    n = 3 * n + 1;
	cnt++;
    }
    printf("\nNumber of hailstones generated: %d\n", cnt);
	
}
